### ISSUE TITLE
Defaults handling not working

### ISSUE THREAD

**Issue by jhmartin** [SimpleFinance/chef-handler-sensu-event#6]
It seems I must pass the server name in the chef_handler directive (localhost) otherwise I get:

[2014-07-18T11:54:57-04:00] ERROR: Report handler Chef::Handler::SensuEvent raised #<SocketError: getaddrinfo: Name or service not known>
[2014-07-18T11:54:57-04:00] ERROR: /var/chef/handlers/chef-handler-sensu-event.rb:41:in `initialize'
[2014-07-18T11:54:57-04:00] ERROR: /var/chef/handlers/chef-handler-sensu-event.rb:41:in`new'
[2014-07-18T11:54:57-04:00] ERROR: /var/chef/handlers/chef-handler-sensu-event.rb:41:in `report'

**Comment by jdinthe** [comment]
Huh, that is unexpected. I think moving to the following style should ensure the defaults always work:

https://github.com/SimpleFinance/chef-handler-spinup-complete/blob/master/lib/chef-handler-spinup-complete.rb#L33

I'll PR this (or you're more than welcome to) later today -- I'm hopping in the car for a couple hours in a moment here, but should be able to get to it in the afternoon.
